# Dockerfile

FROM apache/airflow:2.9.0

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gosu \
    # Dependencies untuk kompilasi psycopg2
    build-essential \
    libpq-dev \
    python3-dev \
    # Hapus cache instalasi
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN gosu airflow:root pip install --no-cache-dir -r /tmp/requirements.txt

USER airflow